CREATE DATABASE data_sekolah;

USE data_sekolah;

CREATE TABLE siswa (
    id INT PRIMARY KEY AUTO_INCREMENT,
    nis INT NOT NULL UNIQUE,
    nama  VARCHAR(255) NOT NULL, 
    alamat VARCHAR(255) NOT NULL, 
    JK VARCHAR(255) NOT NULL, 
    email VARCHAR(255) NOT NULL UNIQUE, 
    telepon VARCHAR(255) NOT NULL UNIQUE, 
    kelas VARCHAR(255) NOT NULL,
    point INT NOT NULL
);

CREATE TABLE guru (
    id INT PRIMARY KEY AUTO_INCREMENT,
    code_guru INT NOT NULL UNIQUE,
    nama  VARCHAR(255) NOT NULL, 
    alamat VARCHAR(255) NOT NULL, 
    JK VARCHAR(255) NOT NULL, 
    email VARCHAR(255) NOT NULL UNIQUE, 
    telepon VARCHAR(255) NOT NULL UNIQUE, 
    kelas VARCHAR(255) NOT NULL
);

CREATE TABLE kejuruan (
  id INT PRIMARY KEY AUTO_INCREMENT, 
  singkatan VARCHAR(255) NOT NULL, 
  nama VARCHAR(255) NOT NULL, 
  code VARCHAR(255) NOT NULL
);

CREATE TABLE kelas (
  id INT PRIMARY KEY AUTO_INCREMENT, 
  kelas VARCHAR(255) NOT NULL, 
  kode_kelas VARCHAR(255) NOT NULL, 
  singkatan VARCHAR(255) NOT NULL
);

CREATE TABLE riwayat_pelanggaran (
  id INT PRIMARY KEY AUTO_INCREMENT, 
  nis INT NOT NULL,
  pelanggaran VARCHAR(255) NOT NULL,
  bobot INT NOT NULL,
  total_poin INT NOT NULL,
  tanggal TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)